name: "Talos Prepare"
description: "Print information related to this CI run."
runs:
  using: "composite"
  steps:
    - shell: bash
      run: >
        echo github.workflow: ${{ github.workflow }} &&
        echo github.job: ${{ github.job }} &&
        echo github.run_id: ${{ github.run_id }} &&
        echo github.run_number: ${{ github.run_number }} &&
        echo github.actor: ${{ github.actor }} &&
        echo github.repository: ${{ github.repository }} &&
        echo github.repository_owner: ${{ github.repository_owner }} &&
        echo github.event_name: ${{ github.event_name }} &&
        echo github.sha: ${{ github.sha }} &&
        echo github.ref: ${{ github.ref }} &&
        echo github.head_ref: ${{ github.head_ref }} &&
        echo github.base_ref: ${{ github.base_ref }} &&
        echo github.workspace: ${{ github.workspace }}
